<?xml version="1.0" encoding="utf-8"?><Database Name="QLVATTU" Class="QLVatTuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLVATTU;User ID=sa;Trust Server Certificate=True" SettingsObjectName="QLVatTu.Properties.Settings" SettingsPropertyName="QLVATTUConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VatTu" Member="VatTus">
    <Type Name="VatTu">
      <Column Name="mavt" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenvt" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nhasx" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ngaysx" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hansd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dongia" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>