#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVatTu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVATTU")]
	public partial class QLVatTuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVatTu(VatTu instance);
    partial void UpdateVatTu(VatTu instance);
    partial void DeleteVatTu(VatTu instance);
    #endregion
		
		public QLVatTuDataContext() : 
				base(global::QLVatTu.Properties.Settings.Default.QLVATTUConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLVatTuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLVatTuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLVatTuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLVatTuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VatTu> VatTus
		{
			get
			{
				return this.GetTable<VatTu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VatTu")]
	public partial class VatTu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mavt;
		
		private string _tenvt;
		
		private string _nhasx;
		
		private System.DateTime _ngaysx;
		
		private int _hansd;
		
		private int _soluong;
		
		private decimal _dongia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmavtChanging(string value);
    partial void OnmavtChanged();
    partial void OntenvtChanging(string value);
    partial void OntenvtChanged();
    partial void OnnhasxChanging(string value);
    partial void OnnhasxChanged();
    partial void OnngaysxChanging(System.DateTime value);
    partial void OnngaysxChanged();
    partial void OnhansdChanging(int value);
    partial void OnhansdChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OndongiaChanging(decimal value);
    partial void OndongiaChanged();
    #endregion
		
		public VatTu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavt", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mavt
		{
			get
			{
				return this._mavt;
			}
			set
			{
				if ((this._mavt != value))
				{
					this.OnmavtChanging(value);
					this.SendPropertyChanging();
					this._mavt = value;
					this.SendPropertyChanged("mavt");
					this.OnmavtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvt", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenvt
		{
			get
			{
				return this._tenvt;
			}
			set
			{
				if ((this._tenvt != value))
				{
					this.OntenvtChanging(value);
					this.SendPropertyChanging();
					this._tenvt = value;
					this.SendPropertyChanged("tenvt");
					this.OntenvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhasx", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nhasx
		{
			get
			{
				return this._nhasx;
			}
			set
			{
				if ((this._nhasx != value))
				{
					this.OnnhasxChanging(value);
					this.SendPropertyChanging();
					this._nhasx = value;
					this.SendPropertyChanged("nhasx");
					this.OnnhasxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysx", DbType="Date NOT NULL")]
		public System.DateTime ngaysx
		{
			get
			{
				return this._ngaysx;
			}
			set
			{
				if ((this._ngaysx != value))
				{
					this.OnngaysxChanging(value);
					this.SendPropertyChanging();
					this._ngaysx = value;
					this.SendPropertyChanged("ngaysx");
					this.OnngaysxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hansd", DbType="Int NOT NULL")]
		public int hansd
		{
			get
			{
				return this._hansd;
			}
			set
			{
				if ((this._hansd != value))
				{
					this.OnhansdChanging(value);
					this.SendPropertyChanging();
					this._hansd = value;
					this.SendPropertyChanged("hansd");
					this.OnhansdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongia", DbType="Decimal(18,2) NOT NULL")]
		public decimal dongia
		{
			get
			{
				return this._dongia;
			}
			set
			{
				if ((this._dongia != value))
				{
					this.OndongiaChanging(value);
					this.SendPropertyChanging();
					this._dongia = value;
					this.SendPropertyChanged("dongia");
					this.OndongiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
