## Importing pandas

### Bắt đầu và kiểm tra thiết lập pandas của bạn

Mức độ: *easy* 

**1.** Import pandas dưới bí danh `pd`.

In [2]:
import pandas as pd

Ba câu tiếp theo khó hơn một chút.


**26.** Trong ô bên dưới, bạn có một DataFrame `df` bao gồm 10 cột số dấu phẩy động. Chính xác 5 mục trong mỗi hàng là giá trị NaN.

Đối với mỗi hàng của DataFrame, hãy tìm *cột* chứa giá trị NaN *thứ ba*.

Bạn nên trả về một Chuỗi nhãn cột: `e, c, d, h, d`

In [3]:
import numpy as np
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# viết một giải pháp cho câu hỏi ở đây
ketqua = df.isna().cumsum( axis = 1).eq(3).idxmax( axis = 1)
print( ketqua )

0    e
1    c
2    d
3    h
4    d
dtype: object


**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [4]:
df1 = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

# write a solution to the question here

ketqua = df1.groupby('grps')['vals'].apply( lambda x: x.nlargest(3).sum() )

print(ketqua)

grps
a    409
b    156
c    345
Name: vals, dtype: int64


**28.** DataFrame `df` được xây dựng bên dưới có hai cột số nguyên 'A' và 'B'. Các giá trị trong 'A' nằm trong khoảng từ 1 đến 100 (bao gồm). 

Đối với mỗi nhóm 10 số nguyên liên tiếp trong 'A' (tức là `(0, 10]`, `(10, 20]`, ...), hãy tính tổng các giá trị tương ứng trong cột 'B'.

Câu trả lời sẽ là một Series như sau:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [5]:
import pandas as pd
df2 = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# viết một giải pháp cho câu hỏi ở đây
df2['A_bins'] = pd.cut(  df2['A'], bins = range(0, 110, 10) )

ketqua = df2.groupby('A_bins', observed = False)['B'].sum()
print(ketqua)

A_bins
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int32


## DataFrames: những vấn đề khó hơn 

### Những điều này có thể đòi hỏi một chút suy nghĩ vượt ra ngoài khuôn khổ...

...nhưng tất cả đều có thể giải quyết được chỉ bằng các phương pháp pandas/NumPy thông thường (và do đó tránh sử dụng vòng lặp `for` rõ ràng)..

Mức độ: *hard*

**29.** Hãy xem xét DataFrame `df` trong đó có một cột số nguyên 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
Đối với mỗi giá trị, hãy đếm ngược lại sự khác biệt đến số không trước đó (hoặc thời điểm bắt đầu của Series, tùy theo giá trị nào gần hơn). Do đó, các giá trị này phải là

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Tạo cột mới này thành cột 'Y'.

In [23]:
df3 = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

group = df3['X'].eq(0).cumsum()

df3['Y'] = df3.groupby(group).cumcount(ascending=True) + 1 # Tính thứ tự ngược lại trong mỗi nhóm

df3.loc[df3['X'] == 0, 'Y'] = 0
print( df3 )

   X  Y
0  7  1
1  2  2
2  0  0
3  3  2
4  4  3
5  2  4
6  5  5
7  0  0
8  3  2
9  4  3


**30.** Hãy xem xét DataFrame được xây dựng bên dưới chứa các hàng và cột dữ liệu số. 

Tạo danh sách các vị trí chỉ mục hàng-cột của 3 giá trị lớn nhất trong DataFrame này. Trong trường hợp này, câu trả lời sẽ là:
```
[(5, 7), (6, 4), (2, 5)]
```

In [27]:
df4 = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))

df4_unstack = df4.unstack()
largest_position = df4_unstack.nlargest(3).index.tolist()
print( largest_position  )

[(2, 5), (5, 7), (6, 4)]


**31.** Bạn được cung cấp DataFrame bên dưới với một cột ID nhóm, 'grps', và một cột chứa các giá trị số nguyên tương ứng, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Tạo một cột mới 'patched_values' chứa các giá trị giống như 'vals' bất kỳ giá trị âm nào trong 'vals' với nhóm mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

In [33]:
df5 = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

trungbinh_group = df5.groupby('grps')['vals'].mean()
df5["patched_vals"] = df5.apply(lambda row: trungbinh_group[row["grps"]] if row["vals"] < 0 else row["vals"], axis=1)

print(df5)

    vals grps  patched_vals
0    -12    A     -0.333333
1     -7    B      6.333333
2    -14    A     -0.333333
3      4    A      4.000000
4     -7    A     -0.333333
5     28    B     28.000000
6     -2    A     -0.333333
7     -1    A     -0.333333
8      8    A      8.000000
9     -2    B      6.333333
10    28    A     28.000000
11    12    A     12.000000
12    16    A     16.000000
13   -24    A     -0.333333
14   -12    A     -0.333333


**32.** Triển khai giá trị trung bình lăn trên các nhóm có kích thước cửa sổ là 3, bỏ qua giá trị NaN. Ví dụ, hãy xem xét DataFrame sau:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
Mục tiêu là tính toán Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. cửa sổ đầu tiên có kích thước ba cho nhóm 'b' có các giá trị 3.0, NaN và 3.0 và xuất hiện ở chỉ mục hàng 5. Thay vì là NaN, giá trị trong cột mới ở chỉ mục hàng này phải là 3.0 (chỉ sử dụng hai giá trị không phải NaN để tính giá trị trung bình (3+3)/2)

In [6]:
df6 = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})

df6['rolling_mean'] = df6.groupby('group')['value'].transform(lambda x: x.rolling(window = 3, min_periods = 1).mean()  )

print(df6)

   group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      b    NaN      3.000000
4      a    2.0      1.666667
5      b    3.0      3.000000
6      b    NaN      3.000000
7      b    1.0      2.000000
8      a    7.0      3.666667
9      b    3.0      2.000000
10     a    NaN      4.500000
11     b    8.0      4.000000


## Series and DatetimeIndex

### Bài tập tạo và thao tác Series với dữ liệu ngày giờ

Mức độ: *easy/medium*

pandas rất tuyệt vời để làm việc với ngày tháng và thời gian. Những câu đố này khám phá một số chức năng này.


**33.** Tạo một DatetimeIndex chứa mỗi ngày làm việc của năm 2015 và sử dụng nó để lập chỉ mục cho một Series số ngẫu nhiên. Chúng ta hãy gọi Series này là `s`.

In [39]:
import pandas as pd
import numpy
date = pd.bdate_range(start = '2015-01-01', end = '2015-12-31')

s = pd.Series(np.random.randn( len(date)), index = date )

print( s )

2015-01-01    0.981890
2015-01-02   -0.596613
2015-01-05   -3.367266
2015-01-06    0.144311
2015-01-07   -0.358256
                ...   
2015-12-25   -0.719155
2015-12-28    0.827802
2015-12-29   -1.510845
2015-12-30    0.288308
2015-12-31   -0.996281
Freq: B, Length: 261, dtype: float64


**34.** Tìm tổng các giá trị trong `s` của mỗi thứ Wednesday.

In [40]:
wednesday = s[ s.index.weekday == 2 ]
sum_wednesday = wednesday.sum()
print(sum_wednesday) 

7.842920028051302


**35.** Đối với mỗi tháng dương lịch trong `s`, hãy tìm giá trị trung bình.

In [41]:
avg_month1 = s.groupby( s.index.month).mean()
print( avg_month1 )

print()

avg_month2 = s.resample('ME').mean()
print( avg_month2)

1    -0.286552
2     0.298895
3     0.250791
4    -0.196747
5    -0.185335
6    -0.168208
7    -0.205844
8    -0.068791
9     0.131703
10    0.564272
11   -0.000753
12    0.091323
dtype: float64

2015-01-31   -0.286552
2015-02-28    0.298895
2015-03-31    0.250791
2015-04-30   -0.196747
2015-05-31   -0.185335
2015-06-30   -0.168208
2015-07-31   -0.205844
2015-08-31   -0.068791
2015-09-30    0.131703
2015-10-31    0.564272
2015-11-30   -0.000753
2015-12-31    0.091323
Freq: ME, dtype: float64


**36.**Đối với mỗi nhóm bốn tháng liên tiếp trong lịch `s`, hãy tìm ngày có giá trị cao nhất.

In [42]:
print ( s.resample( '4ME' ).apply( lambda x: x.idxmax() ) )


2015-01-31   2015-01-22
2015-05-31   2015-02-06
2015-09-30   2015-08-24
2016-01-31   2015-11-06
Freq: 4ME, dtype: datetime64[ns]


**37.** Tạo DateTimeIndex bao gồm thứ Năm tuần thứ ba của mỗi tháng trong các năm 2015 và 2016.

In [44]:
from dateutil.rrule import rrule, MONTHLY, TH
from datetime import datetime
dates = list( rrule( freq = MONTHLY, dtstart = datetime(2015, 1, 1), until = datetime(2016, 12, 31), byweekday = TH(2) ) )

ketqua = pd.DatetimeIndex( dates )
print(ketqua)

DatetimeIndex(['2015-01-08', '2015-02-12', '2015-03-12', '2015-04-09',
               '2015-05-14', '2015-06-11', '2015-07-09', '2015-08-13',
               '2015-09-10', '2015-10-08', '2015-11-12', '2015-12-10',
               '2016-01-14', '2016-02-11', '2016-03-10', '2016-04-14',
               '2016-05-12', '2016-06-09', '2016-07-14', '2016-08-11',
               '2016-09-08', '2016-10-13', '2016-11-10', '2016-12-08'],
              dtype='datetime64[ns]', freq=None)


## Làm sạch dữ liệu

### Làm cho DataFrame dễ làm việc hơn

Mức độ: *easy/medium*

Điều này xảy ra thường xuyên: ai đó cung cấp cho bạn dữ liệu chứa chuỗi string không đúng định dạng, Python, danh sách và dữ liệu bị thiếu. Làm thế nào để bạn sắp xếp chúng để có thể tiếp tục phân tích?

Hãy coi cái được cung cấp này như DataFrame để sử dụng trong các câu sau:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Được định dạng, nó trông như thế này:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(Đây là một số dữ liệu chuyến bay do tác giả bịa ra; nó không có mục đích chính xác theo bất kỳ cách nào.)


**38.** Một số giá trị trong cột **FlightNumber** bị thiếu (chúng là `NaN`). Những con số này có nghĩa là tăng thêm 10 với mỗi hàng nên cần phải đặt 10055 và 10075 vào vị trí. Sửa đổi `df` để điền vào những con số bị thiếu này và biến cột thành một cột số nguyên (thay vì một cột số thực).

In [78]:
import pandas as pd
import numpy as np

df_flight = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

df_flight[ 'FlightNumber' ] = df_flight['FlightNumber'].interpolate().astype(int)
print(df_flight)

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"


**39.** Cột **From\_To** sẽ tốt hơn nếu là hai cột riêng biệt! Tách từng chuỗi trên dấu gạch dưới `_` để tạo một DataFrame tạm thời mới có tên là 'temp' với các giá trị chính xác. Gán tên cột chính xác 'From' và 'To' cho DataFrame tạm thời này.

In [79]:
temp = df_flight['From_To'].str.split( '_', expand = True)

temp.columns = ['From', 'To']
print( temp )

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn


**40.** Lưu ý cách viết hoa tên thành phố được trộn lẫn trong DataFrame tạm thời này 'temp'. Chuẩn hóa các chuỗi sao cho chỉ có chữ cái đầu tiên là chữ hoa (ví dụ: "londON" sẽ trở thành "London".)

In [80]:
temp['From'] = temp['From'].str.title()
temp['To'] = temp['To'].str.title()

print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London


**41.** Xóa cột **From_To** khỏi `df` và đính kèm DataFrame tạm thời 'temp' từ các câu hỏi trước đó.

In [81]:
df_flight = df_flight.drop( columns = 'From_To')
df_flight = pd.concat( [df_flight, temp], axis = 1)
print(df_flight)

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London


**42**. Trong cột **Airline**, bạn có thể thấy một số dấu câu và ký hiệu bổ sung xuất hiện xung quanh tên hãng hàng không. Thực hiện chính xác hóa tên hãng hàng không. Ví dụ: `'(British Airways. )'` phải trở thành `'British Airways'`.

In [82]:
import re
df_flight['Airline'] = df_flight['Airline'].str.replace(r'[^a-zA-Z\n]', '', regex = True).str.strip()
print(df_flight)

   FlightNumber  RecentDelays         Airline      From         To
0         10045      [23, 47]             KLM    London      Paris
1         10055            []       AirFrance    Madrid      Milan
2         10065  [24, 43, 87]  BritishAirways    London  Stockholm
3         10075          [13]       AirFrance  Budapest      Paris
4         10085      [67, 32]        SwissAir  Brussels     London


**43**. Trong cột RecentDelays, các giá trị đã được nhập vào DataFrame dưới dạng danh sách. Chúng tôi muốn mỗi giá trị đầu tiên trong cột riêng của nó, mỗi giá trị thứ hai trong cột riêng của nó, v.v. Nếu không có giá trị thứ N, giá trị sẽ là NaN.

Mở rộng Series của các danh sách thành một DataFrame có tên là `delays`, đổi tên các cột `delay_1`, `delay_2`, v.v. và thay thế cột RecentDelays không mong muốn trong `df` bằng `delays`.

In [83]:
delay_array = pd.DataFrame( df_flight['RecentDelays'].to_list() )

delay_array.columns = [ f'delay {i+1}' for i in range(delay_array.shape[1]) ]

df_flight = pd.concat( [df_flight, delay_array], axis = 1)

df_flight = df_flight.drop( columns = 'RecentDelays' )
print(df_flight)

   FlightNumber         Airline      From         To  delay 1  delay 2  \
0         10045             KLM    London      Paris     23.0     47.0   
1         10055       AirFrance    Madrid      Milan      NaN      NaN   
2         10065  BritishAirways    London  Stockholm     24.0     43.0   
3         10075       AirFrance  Budapest      Paris     13.0      NaN   
4         10085        SwissAir  Brussels     London     67.0     32.0   

   delay 3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN  


Bây giờ DataFrame sẽ trông đẹp hơn nhiều.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

## Sử dụng MultiIndexes

### Vượt ra ngoài DataFrames phẳng với các cấp chỉ mục bổ sung

Mức độ: *medium*

Các bài tập trước đây đã cho chúng ta thấy việc phân tích dữ liệu từ DataFrames được trang bị một mức chỉ mục duy nhất. Tuy nhiên, pandas cũng cung cấp cho bạn khả năng lập chỉ mục dữ liệu của mình bằng cách sử dụng *multiple* mức. Điều này rất giống với việc thêm các chiều mới vào một Series hoặc một DataFrame. Ví dụ, một Series là 1D, nhưng bằng cách sử dụng MultiIndex với 2 mức, chúng ta có được chức năng tương tự như một DataFrame 2D.

Bộ câu hỏi dưới đây khám phá cách bạn có thể sử dụng nhiều cấp chỉ mục để nâng cao khả năng phân tích dữ liệu.

Để khởi động, chúng ta sẽ xem xét một Series có hai mức chỉ số.

**44**. Với các danh sách `letters = ['A', 'B', 'C']` và `numbers = list(range(10))`, hãy xây dựng một đối tượng MultiIndex từ tích của hai danh sách. Sử dụng nó để lập chỉ mục cho một Series các số ngẫu nhiên. Gọi Series này là `s`.

In [84]:
import pandas as pd
import numpy as np

letters = ['A', 'B', 'C'] 
numbers = list(range(10))

multi_index = pd.MultiIndex.from_product( [letters, numbers], names = ['Letter', 'Number'])

S = pd.Series( np.random.randn( len(multi_index)) , index = multi_index)

print(S)

Letter  Number
A       0         0.600053
        1        -1.179745
        2         0.062238
        3         0.758804
        4        -0.576863
        5         1.789857
        6         0.604582
        7        -0.315812
        8         0.394202
        9        -1.080539
B       0        -1.338543
        1        -0.303246
        2         1.059383
        3         0.930830
        4        -2.045441
        5        -0.892134
        6         0.145775
        7        -1.335761
        8        -1.587472
        9         0.851058
C       0         0.295509
        1         1.360659
        2        -0.028519
        3         0.826696
        4         0.108576
        5        -0.857767
        6        -1.035032
        7         1.650751
        8        -1.423043
        9         0.077356
dtype: float64


**45.** Kiểm tra xem chỉ mục của `s` có được sắp xếp theo thứ tự từ điển hay không (đây là thuộc tính cần thiết để lập chỉ mục hoạt động chính xác với MultiIndex).

In [85]:
if ( S.index.is_monotonic_increasing == True ):
    print('Chỉ mục đã được sắp xếp theo thứ tự từ điển')
else:
    print('Chỉ mục chưa được sắp xếp theo thứ tự từ điển')

Chỉ mục đã được sắp xếp theo thứ tự từ điển


**46**. Chọn các nhãn `1`, `3` và `6` từ cấp độ thứ hai của MultiIndexed Series.

In [88]:
S_filtered = S.loc[ :, [1,3,6] ]
print( S_filtered )

Letter  Number
A       1        -1.179745
        3         0.758804
        6         0.604582
B       1        -0.303246
        3         0.930830
        6         0.145775
C       1         1.360659
        3         0.826696
        6        -1.035032
dtype: float64


**47**. Cắt các Series `s`; cắt đến nhãn 'B' cho cấp độ đầu tiên và từ nhãn 5 trở đi cho cấp độ thứ hai.

In [89]:
S_cut = S.loc[ 'B': , 5:]

print(S_cut )

Letter  Number
B       5        -0.892134
        6         0.145775
        7        -1.335761
        8        -1.587472
        9         0.851058
C       5        -0.857767
        6        -1.035032
        7         1.650751
        8        -1.423043
        9         0.077356
dtype: float64


**48**. Tính tổng các giá trị trong `s` cho mỗi nhãn ở cấp độ đầu tiên (bạn sẽ có Series cung cấp tổng cho các nhãn A, B và C).

In [94]:
S_sum1 = S.groupby( level = 0 ).sum()

print(S_sum1)
print()

S_sum2 = S.unstack().sum( axis = 1 )
print(S_sum2)


Letter
A    1.056779
B   -4.515551
C    0.975186
dtype: float64

Letter
A    1.056779
B   -4.515551
C    0.975186
dtype: float64


**49**. Giả sử `sum()` (và các phương pháp khác) không chấp nhận đối số từ khóa `level`. Bạn có thể thực hiện tương đương với `s.sum(level=1)` bằng cách nào khác?

In [96]:
print ( S.groupby( S.index.get_level_values( 1 ) ).sum() )

Number
0   -0.442981
1   -0.122332
2    1.093103
3    2.516330
4   -2.513728
5    0.039957
6   -0.284675
7   -0.000823
8   -2.616313
9   -0.152124
dtype: float64


**50**. Đổi các cấp độ của MultiIndex để chúng ta có một chỉ mục có dạng (chữ cái, số). Series mới này có được sắp xếp theo lexorp đúng không? Nếu không, hãy sắp xếp nó.

In [97]:
S_swaplevel = S.swaplevel( 0 ,1 )
print( S_swaplevel )

Number  Letter
0       A         0.600053
1       A        -1.179745
2       A         0.062238
3       A         0.758804
4       A        -0.576863
5       A         1.789857
6       A         0.604582
7       A        -0.315812
8       A         0.394202
9       A        -1.080539
0       B        -1.338543
1       B        -0.303246
2       B         1.059383
3       B         0.930830
4       B        -2.045441
5       B        -0.892134
6       B         0.145775
7       B        -1.335761
8       B        -1.587472
9       B         0.851058
0       C         0.295509
1       C         1.360659
2       C        -0.028519
3       C         0.826696
4       C         0.108576
5       C        -0.857767
6       C        -1.035032
7       C         1.650751
8       C        -1.423043
9       C         0.077356
dtype: float64
